import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Arusheefee Bandeyri",
  description: "Generated by create next app",
};

export const faruma = localFont({
  src: "./fonts/Faruma.ttf",
  variable: "--font-faruma"
})

export const waheed = localFont({
  src: "./fonts/MVWaheed.otf",
  variable: "--font-waheed"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${faruma.variable} ${waheed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
