import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from 'next/font/google'
import SideBar from "@/components/SideBar";
import "@/app/globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Arusheefee Bandeyri",
  description: "Generated by create next app",
};

export const faruma = localFont({
  src: "../fonts/Faruma.ttf",
  variable: "--font-faruma"
})

export const waheed = localFont({
  src: "../fonts/MVWaheed.otf",
  variable: "--font-waheed"
})

const poppins = Poppins({subsets: ["latin"], weight: "400", variable: "--font-poppins"})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${faruma.variable} ${waheed.variable} ${poppins.variable} antialiased`}
      >
        <div className="rounded-md flex flex-col md:flex-row bg-gray-100 dark:bg-neutral-800 flex-1 border border-neutral-200 dark:border-neutral-700 overflow-x-hidden h-full">
          <SideBar />
          <div className="flex flex-1">
            <div className="p-2 md:p-10 rounded-tl-2xl border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 flex flex-col gap-2 flex-1 w-full h-full">
              <div className="flex w-full">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
